syntax on                                       "vim in color
set nocompatible                                "
set showcmd                                     "
set ruler                                       "
set ignorecase                                  "
set smartcase                                   "
set hlsearch                                    "
set showmatch                                   "
set expandtab                                   "
set shiftwidth=4                                "
set tabstop=4                                   "
set softtabstop=4                               "
set shiftround                                  "
set autoindent                                  "
au FileType py set smartindent                  "
set list listchars=tab:▷⋅,trail:⋅,nbsp:⋅        "
filetype plugin on                              "
set omnifunc=syntaxcomplete#Complete            "
