#!/bin/bash
psql-shortcuts() {
    _sh '\l, \l+' "'list' databases, + for more info"
    _sh '\i <filename>' "'include' reads input from file"
    _sh '\c <dbname>' "'connect' establishes a new connection to a PostgreSQL server"
    _sh '\d, \d+ <dbname>' "'display' lists tables, views, and sequences, + for more info"
    _sh '\d, \d+ <tablename>' "'display' lists table column names, + for more info"
    _sh '\o <filename>' "'output' writes future query results to file; \o for stdout"
    _sh '\e' "'editor' opens a text editor (default: vi)"
    _sh '\s, \s <filename>' "'search(?)' searches command history, save to file optional"
    _sh '\timing' 'toggles timing of commands'
    printf '\n'
    _lng "\copy (<query>) TO '<path>' WITH DELIMITER ','" "'output' query results to csv"
    printf '\n'
    _lng 'SELECT enum_range(NULL::<enumtype>);' "list enum values"
}

_sh() {
    printf '%-22s' $1; printf '\e[1;34m%s\e[0m\n' $2
}

_lng() {
    printf '%-48s' $1; printf '\e[1;34m%s\e[0m\n' $2
}
