#!/bin/bash
,term-shortcuts() {
    __ts 'control + A' 'move to the beginning of line'
    __ts 'control + E' 'move to the end of line'
    __ts 'option (alt) + F' 'move forward a word'
    __ts 'option (alt) + B' 'move backward a word'
    __ts 'control + U' 'cut the line before the cursor'
    __ts 'control + K' 'cut line after the cursor'
    __ts 'control + W' 'cut the word before the cursor'
    __ts 'option (alt) + D' 'cut the word after the cursor'
    __ts 'control + Y' 'paste from buffer'
    __ts 'esc + T' 'transpose the two words before the cursor'
    __ts 'control + R' 'search history'
}

__ts() {
    printf '%-22s' $1; printf '\e[1;34m%s\e[0m\n' $2
}
